# Generated by Django 5.0.3 on 2024-09-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tibetiashop', '0008_commande_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendezvous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('date_rendezvous', models.DateField()),
                ('heure_rendezvous', models.TimeField()),
                ('message', models.TextField(blank=True, null=True)),
                ('service', models.CharField(max_length=100)),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
