# Generated by Django 5.0.3 on 2024-09-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tibetiashop', '0009_rendezvous'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendezvous',
            old_name='date_rendezvous',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='rendezvous',
            old_name='heure_rendezvous',
            new_name='heure',
        ),
        migrations.RenameField(
            model_name='rendezvous',
            old_name='telephone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='date_creation',
        ),
    ]
